"""Original teaching beats for each of the 89 additional course days.

Each record contains a complete example and its expected result, why the
concept matters, a concrete model, execution trace and common error. Keep
pedagogical text here; the renderer never guesses a lesson from a title.
"""

from dataclasses import dataclass, field
import re


@dataclass(frozen=True)
class Day:
    number: int
    slug: str
    title: str
    anchor: str
    code: str
    output: str
    focus: str
    wrong: str
    why: str
    model: str
    walk: str
    trace: str
    pitfall: str
    transfer: str
    forms: dict[str, str] = field(default_factory=dict)
    change: str = "예시의 첫 입력 값을 하나"
    task: str = "같은 입력을 받아 같은 결과를 만드는"

    @property
    def buggy(self) -> str:
        return self.code.replace(self.focus, self.wrong, 1)

    @property
    def modified(self) -> tuple[str, str]:
        overrides = {
            26: ('minutes[1]', 'minutes[2]'),
            62: ('["B"]["prev"]', '["A"]["next"]'),
            65: ('key = 10', 'key = 9'),
            47: ('10\\n20\\n', '10\\n20\\n30\\n'),
            55: ('assert total([10, 20]) == 30', 'assert total([11, 20]) == 31'),
            68: ('print(edges["A"])', 'print(edges["B"])'),
            69: ('print(sorted(seen))', 'print(len(seen))'),
            81: ('dfs("A")', 'dfs("B")'),
            83: ('fields[3]', 'fields[2]'),
            85: ('변수,30,pass', '변수,31,pass'),
            92: ('assert total == 60', 'assert total == 60\nassert len(sessions) == 3'),
        }
        if self.number == 56:
            return (self.code.replace('let s=Session{minutes:30};\n    assert_eq!(s.minutes,30);',
                                      'let s=Session{minutes:31};\n    assert_eq!(s.minutes,31);'),
                    '초기 minutes 값과 assert_eq!의 기대값을 함께 30에서 31로')
        if self.number == 89:
            return self.code.replace('let raw = "30";', 'let raw = "31";'), '입력 문자열 30을 31로'
        if self.number in overrides:
            before, after = overrides[self.number]
            return self.code.replace(before, after, 1), f"{before!r}을 {after!r}로"
        strings = [m.span() for m in re.finditer(r'"(?:\\.|[^"\\])*"|\'(?:\\.|[^\'\\])*\'', self.code)]
        number = next((m for m in re.finditer(r"(?<![A-Za-z_0-9])(\d+)(?![A-Za-z_0-9])", self.code)
                       if not any(start <= m.start() < end for start, end in strings)
                       and not re.search(r"return\s+0\s*;\s*$", self.code[max(0, m.start()-8):m.end()+1])), None)
        if number:
            before = number.group(1)
            after = str(int(before) + 1)
            return self.code[:number.start(1)] + after + self.code[number.end(1):], f"처음 등장하는 숫자를 {before}에서 {after}로"
        literal = re.search(r'"([^"\\]+)"', self.code)
        if literal:
            before = literal.group(1)
            after = before + "!"
            return self.code[:literal.start(1)] + after + self.code[literal.end(1):], f"첫 문자열을 {before!r}에서 {after!r}로"
        raise ValueError(f"Day {self.number} has no editable literal")


def D(number, slug, title, anchor, code, output, focus, wrong, why, model,
      walk, trace, pitfall, transfer, forms=None, change=None, task=None):
    return Day(number, slug, title, anchor, code, output, focus, wrong, why,
               model, walk, trace, pitfall, transfer, forms or {},
               change or "예시의 첫 입력 값을 하나",
               task or f"{title}을 보여 주는")


DAYS = {d.number: d for d in [
    D(2, "output-input", "출력과 입력값의 흐름", "python",
      'name = "요섭"\nprint("안녕,", name)', "안녕, 요섭", "name", '"익명"',
      "프로그램은 입력을 받아 계산하고 결과를 출력해야 쓸모가 있습니다. 처음에는 입력을 변수에 고정해 흐름을 확인합니다.",
      "입력 name은 상자 속 글자이고 print는 그 상자에 적힌 값을 읽어 화면에 보냅니다.",
      "name에 문자열을 저장합니다|print의 두 인수를 차례로 평가합니다|쉼표 사이 공백을 넣어 한 줄로 출력합니다",
      'name="요섭" → print가 name을 읽음 → 안녕, 요섭',
      "변수 이름을 따옴표로 감싸 값 대신 글자 name을 출력함", "입력값을 읽어 출력함",
      {"c":"char 배열과 printf의 %s 형식 사용", "python":"print의 인수 사이에 기본 공백 삽입", "rust":"println!의 {} 자리에 값 전달"}),
    D(3, "c-program", "C 프로그램의 시작점과 printf", "c",
      '#include <stdio.h>\nint main(void) {\n    printf("study: %d\\n", 30);\n    return 0;\n}', "study: 30", "printf", "puts",
      "C는 어느 함수에서 실행을 시작할지 명확히 정해야 합니다. 입출력 헤더와 main의 역할을 읽어야 오류를 찾을 수 있습니다.",
      "main은 프로그램 진입문이고 printf는 형식 문자열의 빈자리에 값을 채워 출력합니다.",
      "stdio.h가 printf 선언을 제공합니다|main 내부에서 %d에 정수 30을 채웁니다|return 0은 정상 종료를 알립니다",
      "main 시작 → %d에 30 대입 → study: 30 출력 → 종료",
      "형식 지정자 %d에 정수 인수를 전달하지 않음", "정수를 지정한 형식으로 출력함",
      {"c":"stdio.h·main·printf(%d)·return 0", "python":"print(30)은 main 선언 없이 실행", "rust":"fn main과 println!(\"{}\", 30)"}),
    D(4, "rust-variables", "Rust의 let과 mut", "rust",
      'fn main() {\n    let mut minutes = 20;\n    minutes += 10;\n    println!("{minutes}");\n}', "30", "mut", "",
      "Rust는 값이 바뀔 수 있는 이름을 명시해서 의도하지 않은 수정을 일찍 잡습니다.",
      "let은 이름을 새 값에 묶고 mut는 같은 바인딩의 값을 바꿀 권한을 줍니다.",
      "let mut로 변경 가능한 정수 바인딩을 만듭니다|+=가 기존 20에 10을 더합니다|println!이 현재 30을 표시합니다",
      "minutes=20 → minutes=30 → 30 출력",
      "mut 없이 같은 바인딩을 다시 대입하려고 함", "변경 가능한 바인딩에 값을 갱신함",
      {"c":"int minutes = 20; minutes += 10;", "python":"minutes = 20; minutes += 10", "rust":"let mut minutes = 20; minutes += 10;"}),
    D(5, "arithmetic", "산술식과 연산 순서", "python",
      'minutes = 20 + 5 * 2\nprint(minutes)', "30", "5 * 2", "(20 + 5) * 2",
      "학습 시간처럼 여러 수를 계산할 때 연산 순서를 틀리면 문법 오류 없이도 잘못된 결과가 나옵니다.",
      "곱셈을 먼저 끝낸 뒤 덧셈을 합니다. 원하는 순서가 다르면 괄호로 묶습니다.",
      "5 곱하기 2가 10이 됩니다|20에 10을 더해 minutes에 저장합니다|print가 30을 출력합니다",
      "5*2=10 → 20+10=30 → 30 출력",
      "왼쪽부터 20+5를 먼저 계산한다고 생각함", "연산자 우선순위대로 계산함",
      {"c":"int minutes = 20 + 5 * 2;", "python":"minutes = 20 + 5 * 2", "rust":"let minutes = 20 + 5 * 2;"}),
    D(6, "conversion", "C 형변환과 나눗셈", "c",
      '#include <stdio.h>\nint main(void) {\n    int total = 5;\n    double average = (double)total / 2;\n    printf("%.1f\\n", average);\n    return 0;\n}', "2.5", "(double)total", "total",
      "정수 나눗셈으로 평균을 내면 소수 부분이 사라질 수 있어 계산 전에 타입을 골라야 합니다.",
      "피연산자 하나를 double로 바꾸면 나눗셈 전체가 실수 나눗셈이 됩니다.",
      "total을 int 5로 시작합니다|캐스트 후 5.0/2.0을 계산합니다|%.1f로 소수 한 자리 2.5를 출력합니다",
      "int 5 → double 5.0 → 5.0/2=2.5",
      "정수끼리 먼저 나누고 결과만 double에 저장함", "나누기 전에 실수로 변환함",
      {"c":"(double)total / count", "python":"total / count는 실수, //는 몫", "rust":"total as f64 / count as f64"}),
    D(7, "foundation-review", "기초 1주차 회상과 오류 찾기", "python",
      'minutes = 20 + 5 * 2\nprint(f"{minutes}분")', "30분", "f\"", '"',
      "변수·출력·연산 순서를 한 번에 회상해야 새 문법을 외우기 전에 빈틈을 발견할 수 있습니다.",
      "값을 계산해 변수에 넣고 f-string의 중괄호를 실제 값으로 치환하는 세 단계를 분리합니다.",
      "5*2를 먼저 계산합니다|minutes에 30을 넣습니다|f-string이 30을 문자열에 끼워 넣습니다",
      "5*2=10 → minutes=30 → 30분 출력",
      "문자열 앞 f를 빼고 {minutes}를 글자 그대로 출력함", "계산한 값을 문자열에 삽입함",
      {"c":"printf(\"%d분\\n\", minutes)", "python":"print(f\"{minutes}분\")", "rust":"println!(\"{minutes}분\")"}),
    D(8, "boolean", "불리언과 논리 연산", "rust",
      'fn main() {\n    let ready = true;\n    let focused = false;\n    println!("{}", ready && !focused);\n}', "true", "&& !focused", "|| focused",
      "여러 조건을 합쳐 행동을 결정할 때 참·거짓을 명확하게 계산해야 합니다.",
      "&&는 두 조건이 모두 참이어야 하고 !는 조건의 참·거짓을 뒤집습니다.",
      "ready는 true입니다|!focused는 !false이므로 true입니다|true && true가 true입니다",
      "ready=true → !focused=true → true 출력",
      "&&와 ||를 혼동해 하나만 참이어도 통과시킴", "두 조건의 논리곱을 구함",
      {"c":"stdbool.h의 bool과 &&, !", "python":"True and not focused", "rust":"true && !focused"}),
    D(9, "formatted-output", "소수점 형식과 출력", "python",
      'score = 2.75\nprint(f"평균 {score:.1f}")', "평균 2.8", ":.1f", "",
      "통계 수치를 표시할 때 계산 값과 화면에 보여 주는 자리 수를 구분해야 합니다.",
      "f-string의 :.1f는 실수 표시를 소수 첫째 자리로 반올림해 형식화합니다. 저장된 score 값은 그대로입니다.",
      "score는 2.75로 저장됩니다|표시할 때 :.1f가 소수 한 자리를 선택합니다|반올림한 2.8을 문자열에 넣습니다",
      "score=2.75 → 표시 자리수 1 → 평균 2.8",
      "출력 형식을 바꾸면 변수에 저장된 실제 값도 바뀐다고 생각함", "표시 형식을 조정함",
      {"c":"printf(\"%.1f\", score)", "python":"f\"{score:.1f}\"", "rust":"format!(\"{score:.1}\")"}),
    D(10, "integer-types", "C 정수 타입과 범위", "c",
      '#include <stdio.h>\n#include <limits.h>\nint main(void) {\n    printf("%d\\n", INT_MAX > 0);\n    return 0;\n}', "1", "INT_MAX", "INT_MIN",
      "C의 정수는 무한히 큰 수가 아니므로 범위를 확인하지 않으면 오버플로로 오류가 생깁니다.",
      "limits.h의 INT_MAX는 현재 플랫폼의 int 최댓값을 표현합니다. 양수 비교는 참이면 1입니다.",
      "limits.h가 범위 매크로를 제공합니다|INT_MAX가 0보다 큰지 비교합니다|참을 1로 출력합니다",
      "INT_MAX는 양수 → 비교 결과 참 → 1 출력",
      "int 최대치에 1을 더해도 안전하게 감싼다고 단정함", "정수 범위를 확인함",
      {"c":"INT_MAX 확인 후 덧셈 전 경계 검사", "python":"int는 필요에 따라 자릿수가 커짐", "rust":"i32::MAX와 checked_add 사용"}),
    D(11, "rust-types", "Rust 숫자 타입과 추론", "rust",
      'fn main() {\n    let minutes: u32 = 30;\n    let seconds = minutes * 60;\n    println!("{seconds}");\n}', "1800", "u32", "i32",
      "시간처럼 음수가 될 수 없는 값에는 타입을 골라 의미와 범위를 함께 표현할 수 있습니다.",
      "u32는 음수가 없는 32비트 정수이고 seconds의 타입은 minutes를 사용하는 식에서 추론됩니다.",
      "minutes를 u32 30으로 선언합니다|u32끼리 30*60을 계산합니다|seconds에 1800을 저장해 출력합니다",
      "minutes: u32=30 → seconds=1800 → 출력",
      "서로 다른 정수 타입을 암묵적으로 섞어도 된다고 생각함", "타입 추론과 정수 연산을 사용함",
      {"c":"unsigned int와 정수 승격 규칙 확인", "python":"정수는 타입 주석 없이 사용 가능", "rust":"u32 명시 후 seconds는 추론"}),
    D(12, "comparison", "값 비교와 경계 포함", "python",
      'minutes = 45\nprint(30 <= minutes <= 60)', "True", "<=", "<",
      "공부 시간 범위처럼 경계가 포함되는 조건은 연산자 하나로 오답이 갈립니다.",
      "30 <= minutes <= 60은 왼쪽·오른쪽 비교를 모두 만족해야 참입니다.",
      "30 <= 45가 참입니다|45 <= 60도 참입니다|두 조건을 연결해 True입니다",
      "30<=45 참 → 45<=60 참 → True",
      "<= 대신 <를 써서 정확히 30 또는 60을 빠뜨림", "양쪽 경계를 포함해 비교함",
      {"c":"30 <= minutes && minutes <= 60", "python":"30 <= minutes <= 60", "rust":"30 <= minutes && minutes <= 60"}),
    D(13, "if-branch", "조건문으로 경로 선택", "python",
      'minutes = 45\nif minutes >= 30:\n    print("목표 달성")\nelse:\n    print("조금 더")', "목표 달성", ">= 30", "< 30",
      "점수가 기준을 넘었는지에 따라 실행할 일을 갈라야 합니다.",
      "if는 조건이 참인 블록만 실행하고 else는 거짓일 때만 실행합니다. 두 블록을 동시에 실행하지 않습니다.",
      "minutes에 45를 넣습니다|45>=30이 참입니다|if 블록을 출력하고 else 블록은 건너뜁니다",
      "minutes=45 → 조건 참 → 목표 달성",
      "들여쓰기를 지워 else 블록도 실행될 거라 생각함", "조건에 따른 한 경로 선택",
      {"c":"if (...) { ... } else { ... }", "python":"if 조건: 들여쓰기 else:", "rust":"if 조건 { ... } else { ... }"}),
    D(14, "branch-review", "분기와 경계조건 회상", "c",
      '#include <stdio.h>\nint main(void) {\n    int minutes = 30;\n    if (minutes >= 30) puts("달성");\n    else puts("미달");\n    return 0;\n}', "달성", ">= 30", "> 30",
      "딱 경계에 있는 입력을 직접 확인하면 비교 연산자와 분기 오류를 빠르게 찾습니다.",
      "30 이상은 30도 포함합니다. 조건의 경계값과 경계 양쪽 값을 세 개의 테스트로 묶습니다.",
      "minutes가 정확히 30입니다|30>=30은 참입니다|달성을 출력하며 else는 실행하지 않습니다",
      "minutes=30 → 경계 포함 → 달성",
      ">로 바꿔 30분을 미달로 잘못 판정함", "경계가 포함되는 분기 검증",
      {"c":"if (minutes >= 30)", "python":"if minutes >= 30:", "rust":"if minutes >= 30 {"}),
    D(15, "match", "Rust match로 경우 나누기", "rust",
      'fn main() {\n    let level = 2;\n    let label = match level { 1 => "입문", 2 => "기본", _ => "심화" };\n    println!("{label}");\n}', "기본", "2 =>", "3 =>",
      "조건 분기가 여러 개일 때 빠진 경우가 없도록 모든 패턴을 명시합니다.",
      "match는 위에서 아래로 비교해 처음 맞는 arm을 선택하며 _는 나머지 모든 값을 받습니다.",
      "level은 2입니다|1 패턴을 건너뛰고 2 패턴을 선택합니다|label에 기본을 저장해 출력합니다",
      "level=2 → 2 arm 선택 → 기본",
      "모든 패턴을 덮지 않아 컴파일이 실패함", "완전한 패턴 분기",
      {"c":"switch와 default, 또는 if/else", "python":"match/case와 case _", "rust":"match와 모든 arm을 덮는 _"}),
    D(16, "for-loop", "범위 반복과 누적", "python",
      'total = 0\nfor minutes in [10, 20, 30]:\n    total += minutes\nprint(total)', "60", "total += minutes", "total = minutes",
      "여러 학습 기록을 한 개씩 더하려면 동일한 코드를 반복문으로 표현합니다.",
      "total은 지금까지 읽은 항목의 합이고, 매 반복 후에도 그 불변식이 유지됩니다.",
      "total=0에서 시작합니다|10·20·30을 차례로 더합니다|루프가 끝나면 60을 출력합니다",
      "total=0 → 10 → 30 → 60",
      "반복마다 total을 새 값으로 덮어써 마지막 항목만 남김", "반복 누적 합계",
      {"c":"for (i=0; i<3; i++) total += a[i]", "python":"for minutes in values", "rust":"for minutes in values { total += minutes; }"}),
    D(17, "while-loop", "while과 종료 조건", "c",
      '#include <stdio.h>\nint main(void) {\n    int n = 3;\n    while (n > 0) { printf("%d ", n); n--; }\n    puts("");\n    return 0;\n}', "3 2 1 ", "n--", "n++",
      "횟수를 미리 정하기 어려운 상황에서도 종료 조건을 유지하며 반복해야 합니다.",
      "매 반복마다 n이 1씩 줄어 0에 가까워집니다. 0이 되면 조건이 거짓이라 멈춥니다.",
      "n=3이고 조건이 참입니다|3·2·1을 출력할 때마다 n을 줄입니다|n=0에서 종료합니다",
      "n=3 → 2 → 1 → 0 종료",
      "n을 줄이지 않아 무한 루프가 됨", "상태를 종료 조건 쪽으로 갱신함",
      {"c":"while (n > 0) { n--; }", "python":"while n > 0: n -= 1", "rust":"while n > 0 { n -= 1; }"}),
    D(18, "loop-break", "Rust loop와 break 값", "rust",
      'fn main() {\n    let mut n = 0;\n    let answer = loop { n += 1; if n == 3 { break n * 2; } };\n    println!("{answer}");\n}', "6", "break n * 2", "break n",
      "반복을 마칠 때 계산 결과를 바로 바깥 표현식에 전달할 수 있습니다.",
      "Rust의 loop는 명시적 break가 실행될 때까지 돌며 break 뒤 값이 loop 표현식의 값입니다.",
      "n은 0에서 출발합니다|1·2는 계속 반복합니다|3에서 break 6으로 종료하여 answer=6입니다",
      "n=0 → 1 → 2 → 3 → answer=6",
      "break 뒤의 값을 무시하고 loop는 언제나 빈 값을 준다고 생각함", "반복 종료 값을 사용함",
      {"c":"while(1)과 별도의 결과 변수", "python":"while True와 결과 변수, break", "rust":"let answer = loop { break 값; }"}),
    D(19, "nested-loop", "중첩 반복의 순서", "python",
      'pairs = []\nfor a in [1, 2]:\n    for b in [3, 4]:\n        pairs.append((a, b))\nprint(pairs)', "[(1, 3), (1, 4), (2, 3), (2, 4)]", "for b", "for a",
      "모든 조합을 나열할 때 바깥 반복 한 번마다 안쪽 반복이 처음부터 실행됩니다.",
      "바깥 a를 고정하고 안쪽 b의 모든 값을 방문한 다음 a를 바꿉니다.",
      "a=1일 때 b=3·4를 기록합니다|a=2일 때 다시 b=3·4를 기록합니다|총 2×2=4쌍입니다",
      "a=1,b=3 → a=1,b=4 → a=2,b=3 → a=2,b=4",
      "안쪽 반복이 전체에서 한 번만 실행된다고 생각함", "두 집합의 모든 조합 생성",
      {"c":"바깥 for 안에 안쪽 for", "python":"들여쓴 두 개의 for", "rust":"for a in ... { for b in ... }"}),
    D(20, "c-functions", "C 함수 매개변수와 반환값", "c",
      '#include <stdio.h>\nint add(int a, int b) { return a + b; }\nint main(void) {\n    printf("%d\\n", add(2, 3));\n    return 0;\n}', "5", "return a + b", "return a - b",
      "같은 계산을 여러 곳에서 쓰려면 입력과 출력을 가진 함수로 분리해야 합니다.",
      "매개변수 a,b는 호출 시 전달된 값이고 return은 계산 결과를 호출한 위치에 돌려줍니다.",
      "main에서 add(2,3)을 호출합니다|함수의 a=2,b=3으로 계산합니다|반환 5를 printf가 출력합니다",
      "인수 2,3 전달 → a+b=5 → 호출 지점에 5 반환",
      "함수 안의 a를 main의 변수와 같은 저장공간이라고 생각함", "입력값을 받아 반환값을 계산함",
      {"c":"int add(int a,int b)", "python":"def add(a,b): return a+b", "rust":"fn add(a:i32,b:i32)->i32 {a+b}"}),
    D(21, "functions-review", "반복과 함수 회상", "python",
      'def total(values):\n    result = 0\n    for value in values:\n        result += value\n    return result\nprint(total([10, 20]))', "30", "result += value", "result = value",
      "한 주의 반복·함수를 직접 결합해 보면 상태 누적과 반환의 차이를 확인할 수 있습니다.",
      "함수 내부 result는 호출마다 새로 시작하며 return이 최종 합계를 호출자에게 전달합니다.",
      "호출 시 값 [10,20]을 전달합니다|result가 0→10→30으로 바뀝니다|return 30을 print가 받습니다",
      "입력 [10,20] → result=10 → result=30 → 출력",
      "반복 안에서 result를 덮어써 마지막 값만 반환함", "반복 계산을 함수로 묶음",
      {"c":"배열과 길이를 인자로 받는 함수", "python":"iterable을 매개변수로 받아 return", "rust":"slice를 빌려 iterator.sum()"}),
    D(22, "rust-return", "Rust 표현식과 함수 반환", "rust",
      'fn doubled(n: i32) -> i32 {\n    n * 2\n}\nfn main() { println!("{}", doubled(7)); }', "14", "n * 2", "n * 3",
      "Rust에서는 마지막 표현식이 함수 반환값이 될 수 있어 문장과 표현식의 차이를 알아야 합니다.",
      "본문 마지막 n*2는 세미콜론이 없어서 i32 값을 돌려줍니다.",
      "doubled(7)에 n=7을 묶습니다|마지막 표현식이 14입니다|main의 println!이 14를 출력합니다",
      "n=7 → 7*2=14 → 반환 14",
      "마지막 표현식에 세미콜론을 붙여 반환형이 ()가 됨", "표현식 결과를 반환함",
      {"c":"return n * 2; 필수", "python":"return n * 2 명시", "rust":"마지막 표현식 n * 2"}),
    D(23, "scope", "지역 변수와 이름의 범위", "python",
      'name = "밖"\ndef show():\n    name = "안"\n    print(name)\nshow()\nprint(name)', "안\n밖", 'name = "안"', 'name = "밖"',
      "함수 안팎의 이름이 같아도 어느 값을 읽는지 구별하지 않으면 예상 결과가 틀립니다.",
      "함수 내부의 지역 name은 바깥 name과 다른 바인딩이고 함수가 끝나면 사라집니다.",
      "바깥 name에 밖을 둡니다|show 내부에 별도의 안을 둬 출력합니다|함수 뒤 바깥의 밖을 출력합니다",
      "바깥=밖 → 안쪽=안 출력 → 바깥=밖 출력",
      "함수 안의 대입이 자동으로 바깥 변수를 바꾼다고 생각함", "지역 범위와 바깥 범위를 구분함",
      {"c":"함수 지역 자동 변수와 파일 범위 변수", "python":"함수 내 대입은 기본적으로 지역 바인딩", "rust":"블록의 let은 해당 범위에 속함"}),
    D(24, "recursion", "재귀와 종료 조건", "c",
      '#include <stdio.h>\nint sum_to(int n) {\n    if (n == 0) return 0;\n    return n + sum_to(n - 1);\n}\nint main(void) { printf("%d\\n", sum_to(3)); return 0; }', "6", "n == 0", "n == -1",
      "큰 문제를 같은 모양의 작은 문제로 줄일 수 있으면 재귀로 관계를 표현할 수 있습니다.",
      "기저 조건 n=0이 멈추는 바닥이고 각 호출은 n을 1 줄여 그 바닥으로 접근합니다.",
      "sum_to(3)이 3+sum_to(2)를 기다립니다|2+sum_to(1), 1+sum_to(0)를 거칩니다|0에서 돌아와 1+2+3=6입니다",
      "sum_to(3) → sum_to(2) → sum_to(1) → sum_to(0) → 6",
      "기저 조건이 없거나 입력을 줄이지 않아 끝없이 호출함", "문제를 줄여 재귀적으로 합산함",
      {"c":"if (n==0) return 0;", "python":"if n==0: return 0", "rust":"if n==0 {0} else {n+sum_to(n-1)}"}),
    D(25, "result-error", "Rust Result와 실패 전달", "rust",
      'fn parse_minutes(text: &str) -> Result<u32, std::num::ParseIntError> {\n    text.parse::<u32>()\n}\nfn main() {\n    match parse_minutes("30") { Ok(n) => println!("{n}"), Err(_) => println!("오류") }\n}', "30", '"30"', '"x"',
      "외부에서 받은 글자는 잘못된 숫자일 수 있어 정상 값과 실패 이유를 분리해야 합니다.",
      "Result는 성공 Ok(값) 또는 실패 Err(오류) 중 하나이며 match가 양쪽을 처리합니다.",
      "문자열 30을 u32로 파싱합니다|Ok(30)이 생성됩니다|match의 Ok arm에서 30을 출력합니다",
      "문자열 30 → Ok(30) → 30 출력",
      "unwrap으로 잘못된 입력에서 프로그램을 종료시킴", "파싱 성공과 실패를 분리함",
      {"c":"strtoul와 endptr/errno 검증", "python":"int(text)와 ValueError 처리", "rust":"parse::<u32>()의 Result match"}),
    D(26, "c-array", "C 배열과 인덱스", "c",
      '#include <stdio.h>\nint main(void) {\n    int minutes[3] = {10, 20, 30};\n    printf("%d\\n", minutes[1]);\n    return 0;\n}', "20", "[1]", "[3]",
      "여러 값을 순서대로 저장하려면 연속된 메모리의 배열과 유효 인덱스를 알아야 합니다.",
      "길이 3 배열의 첫 원소는 0번이고 마지막은 2번입니다. 1번은 두 번째 값입니다.",
      "배열에 10·20·30을 순서대로 저장합니다|인덱스 1을 읽어 20을 얻습니다|printf가 출력합니다",
      "인덱스 0=10 → 인덱스 1=20 → 출력",
      "길이 3의 마지막 인덱스를 3으로 착각해 범위 밖을 읽음", "배열 위치로 값 조회",
      {"c":"int a[3]와 a[1]", "python":"list의 a[1], 범위 밖은 IndexError", "rust":"[i32;3]의 a[1], 범위 밖 검사"}),
    D(27, "python-list", "Python list 추가와 순회", "python",
      'minutes = [10, 20]\nminutes.append(30)\nprint(sum(minutes))', "60", "append(30)", "pop(30)",
      "기록 개수가 늘어날 수 있으면 크기를 바꿀 수 있는 순서 자료구조가 편리합니다.",
      "list는 원소를 순서대로 담고 append는 맨 끝에 새 원소를 넣습니다.",
      "[10,20]으로 시작합니다|끝에 30을 추가해 길이 3이 됩니다|sum이 60을 반환합니다",
      "[10,20] → [10,20,30] → 60",
      "append의 반환값을 새 리스트라고 생각함", "가변 시퀀스의 끝에 추가함",
      {"c":"용량과 길이를 직접 관리하는 배열", "python":"list.append와 sum", "rust":"Vec::push와 iter().sum()"}),
    D(28, "vec-review", "배열·리스트·Vec 회상", "rust",
      'fn main() {\n    let mut minutes = vec![10, 20];\n    minutes.push(30);\n    println!("{}", minutes.iter().sum::<i32>());\n}', "60", "push(30)", "pop()",
      "크기가 바뀌는 컬렉션을 비교하면 저장 용량, 길이, 인덱스 안전성의 차이를 드러낼 수 있습니다.",
      "Vec는 가변 길이의 연속 원소를 담고 push는 끝에 넣습니다. sum은 iterator의 값을 더합니다.",
      "Vec [10,20]을 만듭니다|push(30)으로 [10,20,30]이 됩니다|순회해 합 60을 출력합니다",
      "[10,20] → [10,20,30] → 60",
      "Vec의 원소 추가에 불변 바인딩을 사용함", "가변 벡터를 순회해 합산함",
      {"c":"int 배열·용량·현재 길이를 따로 유지", "python":"list.append와 sum", "rust":"let mut Vec와 push, iter().sum()"}),
    D(30, "pointer-arithmetic", "C 포인터 이동과 배열", "c",
      '#include <stdio.h>\nint main(void) {\n    int values[] = {10, 20, 30};\n    int *p = values;\n    printf("%d\\n", *(p + 1));\n    return 0;\n}', "20", "p + 1", "p + 3",
      "배열의 연속 원소에 주소로 접근할 때 이동 단위가 바이트가 아니라 원소 크기임을 알아야 합니다.",
      "int 포인터 p+1은 다음 int 원소의 주소입니다. 역참조는 그 주소에 저장된 값을 읽습니다.",
      "p가 values[0]을 가리킵니다|p+1은 두 번째 원소를 가리킵니다|역참조해 20을 출력합니다",
      "p=&values[0] → *p=10 → p+1=&values[1] → *(p+1)=20 → 20 출력",
      "배열 끝을 지난 주소를 역참조함", "배열 내부에서 다음 원소를 참조함",
      {"c":"*(p+1)은 values[1]", "python":"values[1]로 경계 검사", "rust":"slice.get(1)은 Option<&T>"}),
    D(31, "alias-copy", "Python 별칭과 얕은 복사", "python",
      'source = [10, 20]\ncopy = source.copy()\ncopy[0] = 99\nprint(source[0])', "10", "source.copy()", "source",
      "두 변수가 같은 리스트를 공유하면 한쪽 수정이 다른 쪽에 보이므로 복사 여부를 판단해야 합니다.",
      "copy()는 새 바깥 리스트를 만들고, 단순 대입은 같은 리스트에 새 이름만 붙입니다.",
      "source에 두 원소가 있습니다|copy()가 다른 리스트를 만듭니다|copy[0]만 99가 되어 source[0]은 10입니다",
      "source=[10,20] → copy=[10,20] → copy=[99,20] → source[0]=10",
      "copy = source를 독립된 리스트 복사라고 생각함", "원본과 새 리스트를 구분함",
      {"c":"배열을 원소별 복사하거나 memcpy 길이 확인", "python":"list.copy는 얕은 복사", "rust":"Vec::clone은 새 소유 데이터"}),
    D(32, "move-clone", "Rust 소유권 이동과 clone", "rust",
      'fn main() {\n    let original = String::from("study");\n    let copy = original.clone();\n    println!("{original} {copy}");\n}', "study study", "clone()", "",
      "힙 데이터를 가진 값을 다른 변수에 대입하면 누가 해제하는지 소유권 규칙을 알아야 합니다.",
      "clone은 내용을 새 메모리에 복제해 두 String이 각각 소유하게 합니다. 단순 대입은 소유권을 이동합니다.",
      "original이 study를 소유합니다|clone으로 별도 String을 만듭니다|두 바인딩 모두 유효해 출력합니다",
      "original 소유 → clone 별도 소유 → 둘 다 출력",
      "String을 이동한 뒤 이전 변수를 다시 사용함", "새 소유 복사본 생성",
      {"c":"malloc과 복사·free 책임을 명시", "python":"문자열은 불변, 이름 재바인딩", "rust":"move 후 이전 값 사용 불가, clone은 복제"}),
    D(33, "shared-borrow", "공유 빌림과 참조", "rust",
      'fn length(text: &String) -> usize { text.len() }\nfn main() {\n    let topic = String::from("Rust");\n    println!("{} {topic}", length(&topic));\n}', "4 Rust", "&topic", "topic.clone()",
      "함수에 값을 넘긴 뒤에도 호출자가 계속 사용하려면 복제 없이 읽기만 빌려줄 수 있습니다.",
      "&String은 소유권을 가져가지 않는 공유 참조이고 호출이 끝나도 topic의 소유자는 main입니다.",
      "topic이 Rust를 소유합니다|length가 주소를 읽기 전용으로 빌립니다|길이 4와 원본 Rust를 출력합니다",
      "topic 소유 → &topic 빌림 → 길이 4 → topic 여전히 유효",
      "참조를 값 이동과 똑같이 생각해 원본을 쓰지 못한다고 판단함", "소유권 이동 없이 읽기 전달",
      {"c":"const char *를 넘기고 수명 책임 유지", "python":"객체 참조가 전달되고 가변성에 주의", "rust":"&String, 일반적으로 &str 빌림"}),
    D(34, "array-pointer", "C 배열 매개변수와 길이", "c",
      '#include <stdio.h>\n#include <stddef.h>\nint sum(const int *a, size_t n) { int out=0; for (size_t i=0;i<n;i++) out+=a[i]; return out; }\nint main(void) { int a[]={2,4,6}; printf("%d\\n",sum(a,3)); return 0; }', "12", "i<n", "i<=n",
      "함수에 C 배열을 전달하면 배열 길이가 자동으로 따라가지 않아 별도의 길이 인자가 필요합니다.",
      "a는 첫 원소를 가리키고 n은 읽을 수 있는 원소 개수입니다. 인덱스는 0부터 n-1까지입니다.",
      "a의 첫 주소와 길이 3을 전달합니다|i=0,1,2에서 2+4+6을 누적합니다|i=3에서 멈추고 12를 반환합니다",
      "i=0 out=2 → i=1 out=6 → i=2 out=12",
      "배열 끝 인덱스를 n으로 착각해 한 칸 넘겨 읽음", "배열과 길이를 함께 전달함",
      {"c":"const int *a, size_t n", "python":"list 객체가 길이를 알고 len(a) 가능", "rust":"&[i32] slice가 길이를 보유"}),
    D(35, "ownership-review", "주소와 소유권 회상", "python",
      'items = [1, 2]\nalias = items\nalias.append(3)\nprint(items)', "[1, 2, 3]", "alias = items", "alias = items.copy()",
      "포인터·참조·복사의 차이를 스스로 설명할 수 있어야 공유 상태의 버그를 찾아냅니다.",
      "두 이름이 같은 가변 리스트를 가리키면 어느 이름을 통해 바꿔도 같은 객체가 수정됩니다.",
      "items가 리스트를 가리킵니다|alias가 동일 객체를 가리킵니다|append가 그 객체를 변경해 items에서도 3이 보입니다",
      "items→리스트 → alias→같은 리스트 → append → [1,2,3]",
      "새 이름을 붙이면 무조건 별도의 객체가 생긴다고 생각함", "공유 참조와 복사를 구별함",
      {"c":"포인터 복사는 주소 공유, 별도 malloc 필요", "python":"대입은 별칭, copy는 새 리스트", "rust":"move·&·clone 중 의도 선택"}),
    D(36, "rust-slices", "Rust 슬라이스와 범위", "rust",
      'fn main() {\n    let values = [10, 20, 30, 40];\n    let middle = &values[1..3];\n    println!("{} {}", middle[0], middle[1]);\n}', "20 30", "1..3", "1..4",
      "배열 일부를 복사하지 않고 읽을 때 시작·끝 인덱스의 의미를 정확히 알아야 합니다.",
      "슬라이스 [1..3]은 시작 1을 포함하고 끝 3은 제외하므로 원소 20,30을 빌립니다.",
      "원본 배열을 저장합니다|인덱스 1과 2를 빌립니다|middle[0],middle[1]이 20,30입니다",
      "[10,20,30,40] → [20,30] 빌림 → 20 30",
      "끝 인덱스 3도 포함한다고 생각함", "복사 없이 부분 범위를 빌림",
      {"c":"포인터 시작 위치와 길이를 함께 전달", "python":"values[1:3]은 새 리스트 생성", "rust":"&values[1..3]은 빌림"}),
    D(37, "c-strings", "C 문자열과 널 종료", "c",
      '#include <stdio.h>\n#include <string.h>\nint main(void) {\n    char word[] = "cat";\n    printf("%zu\\n", strlen(word));\n    return 0;\n}', "3", "strlen(word)", "sizeof(word)",
      "C 문자열은 단순 char 배열과 달리 끝을 알리는 널 문자까지 공간이 필요합니다.",
      "word에는 c,a,t,\\0 네 바이트가 들어 있고 strlen은 널 이전의 글자 세 개만 셉니다.",
      "배열 크기는 널 포함 4입니다|strlen이 널까지 전진합니다|널 이전 길이 3을 출력합니다",
      "c a t \\0 → strlen=3 → 출력",
      "널 종료가 없는 버퍼를 strlen에 넘겨 범위 밖을 읽음", "널 종료된 문자열 길이 계산",
      {"c":"char[]와 '\\0', strlen", "python":"str은 길이를 직접 관리", "rust":"String.len은 UTF-8 바이트 길이"}),
    D(38, "unicode", "Python 문자열과 유니코드", "python",
      'text = "한글"\nprint(len(text), len(text.encode("utf-8")))', "2 6", "encode(\"utf-8\")", "upper()",
      "글자 수와 저장 바이트 수를 혼동하면 파일 길이나 자르기 계산이 틀립니다.",
      "Python str의 len은 코드 포인트 수이고 UTF-8로 인코딩한 bytes 길이는 별개입니다.",
      "text에는 한·글 두 글자가 있습니다|UTF-8로 각 글자를 3바이트로 인코딩합니다|2와 6을 출력합니다",
      "두 글자 → UTF-8 6바이트 → 2 6",
      "한글 한 글자를 항상 한 바이트라고 가정함", "문자 수와 인코딩 바이트 수 구분",
      {"c":"UTF-8 char[]의 strlen은 바이트 수", "python":"len(str)과 len(encode()) 구별", "rust":"len은 바이트, chars().count()는 scalar 수"}),
    D(39, "string-slice", "Rust String과 &str", "rust",
      'fn main() {\n    let mut topic = String::from("C");\n    topic.push_str(" Rust");\n    let view: &str = &topic;\n    println!("{view}");\n}', "C Rust", "push_str", "push",
      "수정 가능한 소유 문자열과 읽기만 하는 문자열 뷰의 역할을 구분해야 합니다.",
      "String은 가변 힙 데이터를 소유하고 &str은 그 문자열의 유효 구간을 빌립니다.",
      "topic이 C를 소유합니다|push_str이 공백과 Rust를 덧붙입니다|view로 전체를 빌려 출력합니다",
      "topic=C → topic=C Rust → view=C Rust",
      "&str 참조로 원본의 크기를 바꿀 수 있다고 생각함", "소유 문자열을 수정하고 읽기 전용 뷰 사용",
      {"c":"가변 char 버퍼는 용량 검사 필요", "python":"불변 str 연결은 새 문자열", "rust":"String.push_str 후 &str 빌림"}),
    D(40, "malloc-free", "C 동적 할당과 해제", "c",
      '#include <stdio.h>\n#include <stdlib.h>\nint main(void) {\n    int *value = malloc(sizeof *value);\n    if (!value) return 1;\n    *value = 42;\n    printf("%d\\n", *value);\n    free(value);\n    return 0;\n}', "42", "free(value)", "free(NULL)",
      "필요한 메모리를 실행 중 할당하면 실패 검사와 정확히 한 번 해제할 책임이 생깁니다.",
      "malloc은 힙 공간의 주소 또는 NULL을 돌려주고 free 후에는 해당 주소를 다시 역참조할 수 없습니다.",
      "int 크기만큼 할당합니다|NULL 검사를 거쳐 42를 저장하고 출력합니다|사용을 마친 뒤 free합니다",
      "malloc → NULL 검사 → 저장·출력 → free",
      "free 뒤 포인터를 다시 역참조하거나 해제를 빼먹음", "동적 메모리 수명 관리",
      {"c":"malloc 실패 검사와 free 대응", "python":"객체 수명은 런타임이 관리", "rust":"Box/Vec가 scope 종료 시 Drop"}),
    D(41, "box", "Rust Box와 힙 소유", "rust",
      'fn main() {\n    let boxed = Box::new(40);\n    let answer = *boxed + 2;\n    println!("{answer}");\n}', "42", "*boxed", "boxed",
      "크기가 큰 값이나 재귀적 구조를 힙에 저장할 때 누가 소유하는지 알아야 합니다.",
      "Box<T>는 힙 값의 유일한 소유자이고 *는 안쪽 값을 읽습니다. scope가 끝나면 자동으로 해제합니다.",
      "Box가 40을 힙에 저장합니다|역참조로 40을 얻어 2를 더합니다|42를 출력하고 scope 끝에서 해제합니다",
      "Box(40) → 역참조 40 → 42 → Drop",
      "Box를 C의 raw pointer처럼 직접 free해야 한다고 생각함", "힙 값의 안전한 소유",
      {"c":"malloc/free를 직접 짝지음", "python":"참조된 객체는 런타임 관리", "rust":"Box::new와 자동 Drop"}),
    D(42, "memory-review", "메모리 모델 종합 회상", "python",
      'a = [1]\nb = a.copy()\nb.append(2)\nprint(a, b)', "[1] [1, 2]", "a.copy()", "a",
      "주소 공유와 독립 복사를 손으로 구분하고 수명에 따라 안전한 방법을 선택합니다.",
      "b는 새 바깥 리스트를 소유한 참조이므로 append는 a를 바꾸지 않습니다.",
      "a=[1]입니다|copy로 b=[1]을 새로 만듭니다|b만 [1,2]가 되어 함께 출력합니다",
      "a=[1] → b=[1] 별도 객체 → b=[1,2]",
      "얕은 복사를 중첩 리스트의 깊은 복사로 착각함", "복사 범위와 공유 상태 확인",
      {"c":"포인터 주소 복사와 버퍼 내용 복사는 다름", "python":"list.copy는 중첩 원소까지 복제하지 않음", "rust":"clone의 구현이 무엇을 복사하는지 확인"}),
    D(43, "output-parameter", "C 포인터로 결과 돌려주기", "c",
      '#include <stdio.h>\nint double_into(int input, int *out) {\n    if (!out) return 0;\n    *out = input * 2; return 1;\n}\nint main(void) { int n=0; if(double_into(6,&n)) printf("%d\\n",n); return 0; }', "12", "*out =", "out =",
      "C 함수에서 성공 여부와 계산 결과를 동시에 돌려주려면 주소를 통한 출력 인자를 사용할 수 있습니다.",
      "out은 호출자 n의 주소입니다. *out에 대입해야 호출자 변수의 값이 바뀝니다.",
      "main이 &n을 전달합니다|함수가 NULL을 확인합니다|*out으로 n=12를 만들고 성공을 반환합니다",
      "n=0 → &n 전달 → *out=12 → n 출력",
      "out 자체에 대입하고 호출자 변수도 바뀌었다고 생각함", "출력 인자로 호출자 값을 수정함",
      {"c":"int *out과 성공 bool/int 반환", "python":"튜플로 성공·결과를 반환", "rust":"Result<i32,E>로 결과 전달"}),
    D(44, "mutable-arguments", "Python 함수의 가변 인자", "python",
      'def add_session(items):\n    items.append(30)\nvalues = [10]\nadd_session(values)\nprint(values)', "[10, 30]", "items.append(30)", "items = [30]",
      "함수 호출 뒤 원본 리스트가 바뀌는 이유를 알아야 예상치 못한 부작용을 막습니다.",
      "함수 매개변수 items와 호출자 values가 같은 가변 리스트를 참조합니다. append는 객체를 바꿉니다.",
      "values가 [10]을 참조합니다|items가 같은 객체를 가리킵니다|append 뒤 [10,30]이 됩니다",
      "values→[10] → items→같은 객체 → append → [10,30]",
      "매개변수 대입과 객체 내부 수정을 같은 동작으로 혼동함", "가변 객체의 공유 부작용 구분",
      {"c":"int *와 명시적 포인터 전달", "python":"가변 객체 참조를 전달", "rust":"&mut Vec<i32>를 명시적으로 빌림"}),
    D(45, "lifetime", "Rust 참조의 유효 수명", "rust",
      'fn longer<\'a>(x: &\'a str, y: &\'a str) -> &\'a str {\n    if x.len() >= y.len() { x } else { y }\n}\nfn main() { println!("{}", longer("study", "log")); }', "study", "'a", "'static",
      "둘 중 하나의 참조를 반환하는 함수는 결과가 얼마나 오래 유효한지 호출자에게 알려야 합니다.",
      "'a는 반환 참조가 입력 참조들이 함께 유효한 범위를 넘지 않겠다는 관계를 표시합니다.",
      "study 길이는 5, log 길이는 3입니다|첫 참조를 선택합니다|유효한 문자열 study를 출력합니다",
      "x 길이 5 → y 길이 3 → x 반환 → study",
      "지역에서 만든 String의 참조를 함수 밖으로 반환함", "입력 참조와 반환 참조 수명 관계 명시",
      {"c":"호출자가 반환 포인터의 수명을 직접 확인", "python":"참조 수명을 런타임이 관리", "rust":"반환 참조와 입력 참조의 lifetime 연결"}),
    D(46, "c-file", "C 파일 입출력과 실패 검사", "c",
      '#include <stdio.h>\nint main(void) {\n    FILE *f = tmpfile();\n    if (!f) return 1;\n    fputs("30\\n", f); rewind(f);\n    int n=0;\n    if (fscanf(f,"%d",&n)==1) printf("%d\\n",n);\n    fclose(f); return 0;\n}', "30", "rewind(f)", "fclose(f)",
      "파일의 읽기·쓰기는 실패할 수 있고 현재 읽는 위치가 어디인지에 따라 결과가 달라집니다.",
      "쓰고 난 뒤 스트림 위치는 끝입니다. rewind로 처음으로 옮겨야 새 내용을 읽을 수 있습니다.",
      "tmpfile이 임시 파일을 엽니다|30을 쓰고 위치를 처음으로 돌립니다|fscanf 성공 후 출력하고 닫습니다",
      "열기 → 쓰기 → rewind → 읽기 → 닫기",
      "쓰기 직후 위치를 되돌리지 않고 읽어 EOF를 만남", "파일 포인터 위치와 실패를 관리함",
      {"c":"FILE*, 반환값 검사, fclose", "python":"with open은 종료 시 자동 닫기", "rust":"File과 Result, drop으로 닫기"}),
    D(47, "python-file", "Python 파일형 객체와 예외", "python",
      'from io import StringIO\nstream = StringIO("10\\n20\\n")\nvalues = [int(line) for line in stream]\nprint(sum(values))', "30", "int(line)", "line",
      "CSV/텍스트 파일을 읽을 때 줄은 문자열이므로 숫자 변환 실패까지 생각해야 합니다.",
      "StringIO는 메모리 속 파일형 객체입니다. 실제 파일로 바꿔도 한 줄씩 읽는 규칙은 같습니다.",
      "첫 줄 10을 문자열로 읽습니다|각 줄을 int로 바꾸어 [10,20]을 만듭니다|sum이 30입니다",
      "문자열 줄 → int 변환 → [10,20] → 합 30",
      "문자열을 숫자로 바꾸지 않고 합하려고 함", "텍스트 스트림을 순회하고 변환함",
      {"c":"fgets 후 strtol과 변환 오류 검사", "python":"with open 또는 StringIO, int의 ValueError", "rust":"BufRead::lines와 parse의 Result"}),
    D(48, "rust-reader", "Rust 읽기와 Result", "rust",
      'use std::io::{Cursor, Read};\nfn main() {\n    let mut source = Cursor::new("30");\n    let mut text = String::new();\n    source.read_to_string(&mut text).expect("읽기 실패");\n    println!("{text}");\n}', "30", "read_to_string", "read_exact",
      "파일을 읽는 API는 실패할 수 있어 반환된 Result의 성공/실패를 확인해야 합니다.",
      "Cursor는 메모리 버퍼를 파일처럼 읽게 합니다. read_to_string은 text를 변경하고 Result를 돌려줍니다.",
      "Cursor에 30을 넣습니다|가변 문자열 text에 내용을 읽습니다|성공을 확인하고 30을 출력합니다",
      "source=30 → text 비어 있음 → read 성공 text=30",
      "읽기 결과의 오류를 무시해 빈 데이터를 정상으로 취급함", "읽기 결과와 목적 버퍼를 처리함",
      {"c":"fread 반환된 길이와 ferror 확인", "python":"read와 OSError 처리", "rust":"Read::read_to_string의 Result"}),
    D(49, "memory-io-review", "메모리와 입출력 회상", "c",
      '#include <stdio.h>\nint main(void) {\n    int minutes = 30;\n    int *view = &minutes;\n    printf("%d\\n", *view);\n    return 0;\n}', "30", "*view", "view",
      "값·주소·입출력 세 단계를 다시 추적해 포인터가 가리키는 값을 말로 설명합니다.",
      "view의 값은 minutes의 주소이고 *view의 값은 그 주소에 저장된 정수 30입니다.",
      "minutes에 30을 저장합니다|view에 &minutes를 담습니다|*view를 읽어 30을 출력합니다",
      "minutes=30 → view=&minutes → *view=30",
      "포인터 값(주소)과 역참조 결과(정수)를 같은 타입으로 혼동함", "주소를 통해 저장된 값 읽기",
      {"c":"&로 주소, *로 역참조", "python":"이름이 객체를 참조하며 주소 문법 숨김", "rust":"&로 빌림, *로 역참조 가능"}),
    D(50, "c-struct", "C 구조체로 관련 값 묶기", "c",
      '#include <stdio.h>\ntypedef struct { int minutes; int focused; } Session;\nint main(void) {\n    Session s = {30, 1};\n    printf("%d\\n", s.minutes);\n    return 0;\n}', "30", "s.minutes", "s.focused",
      "학습 기록의 시간과 집중 여부가 함께 움직여야 하면 이름 있는 구조체로 묶습니다.",
      "Session은 두 필드의 형식이고 s는 그 형식으로 만든 실제 값입니다. 점 연산자가 필드를 선택합니다.",
      "Session 타입을 정의합니다|s에 시간 30과 집중 1을 초기화합니다|s.minutes를 읽어 출력합니다",
      "타입 정의 → s={30,1} → s.minutes=30",
      "필드 선언 순서와 초기화 값 순서를 혼동함", "관련 필드를 하나의 값으로 묶음",
      {"c":"typedef struct과 s.minutes", "python":"dataclass 또는 class 속성", "rust":"struct Session {minutes:i32,...}"}),
    D(51, "python-class", "Python 클래스와 인스턴스", "python",
      'class Session:\n    def __init__(self, minutes):\n        self.minutes = minutes\ns = Session(30)\nprint(s.minutes)', "30", "self.minutes", "minutes",
      "여러 학습 기록에 같은 데이터 형식과 동작을 적용하려면 클래스로 설계합니다.",
      "클래스는 객체의 설계도이고 self는 지금 만들고 있는 바로 그 객체입니다.",
      "Session(30)이 새 인스턴스를 만듭니다|__init__에서 그 객체의 minutes에 30을 저장합니다|s.minutes로 읽습니다",
      "클래스 정의 → s 생성 → s.minutes=30 → 출력",
      "self를 빼고 지역 변수만 저장해 객체에 값이 남지 않음", "인스턴스 속성 초기화",
      {"c":"struct와 초기화 함수", "python":"__init__(self)와 self.field", "rust":"struct와 impl 생성 함수"}),
    D(52, "rust-method", "Rust 구조체와 메서드", "rust",
      'struct Session { minutes: u32 }\nimpl Session { fn doubled(&self) -> u32 { self.minutes * 2 } }\nfn main() { let s=Session{minutes:30}; println!("{}",s.doubled()); }', "60", "&self", "self",
      "데이터와 관련 계산을 한 곳에 두면 사용자가 필드의 의미를 추적하기 쉽습니다.",
      "impl의 &self는 소유권을 가져가지 않고 구조체 값을 읽는 메서드 수신자입니다.",
      "minutes=30인 Session을 만듭니다|doubled가 s를 빌려 30*2를 계산합니다|60을 출력합니다",
      "s.minutes=30 → &s 빌림 → 60 반환",
      "읽기 전용 메서드에 self를 써 소유권을 불필요하게 이동함", "데이터에 연결된 읽기 메서드",
      {"c":"struct를 받는 함수와 const 포인터", "python":"self를 받는 인스턴스 메서드", "rust":"impl Session와 &self"}),
    D(53, "rust-enum", "Rust enum으로 상태 표현", "rust",
      'enum ResultLabel { Pass, Retry }\nfn main() {\n    let state = ResultLabel::Pass;\n    let label = match state { ResultLabel::Pass => "통과", ResultLabel::Retry => "재시도" };\n    println!("{label}");\n}', "통과", "ResultLabel::Pass", "ResultLabel::Retry",
      "서로 배타적인 상태를 문자열에 제각각 적으면 오타와 빠진 분기가 생깁니다.",
      "enum은 정해진 경우만 값으로 만들게 하고 match는 모든 경우를 처리하게 합니다.",
      "Pass 상태를 선택합니다|match가 Pass arm을 실행합니다|통과를 출력합니다",
      "state=Pass → Pass arm → 통과",
      "가능한 enum 경우를 match에서 하나 빠뜨림", "한정된 상태를 타입으로 표현",
      {"c":"enum과 switch의 모든 경우 확인", "python":"Enum 또는 명시적 분기", "rust":"enum과 exhaustive match"}),
    D(54, "trait-generic", "Rust trait과 제네릭", "rust",
      'fn show<T: std::fmt::Display>(value: T) { println!("{value}"); }\nfn main() { show(30); }', "30", "Display", "Debug",
      "여러 자료형에 같은 출력 기능을 적용할 때 지원할 동작을 계약으로 명시합니다.",
      "T는 타입 매개변수이고 Display 제약은 그 값이 사용자용 문자열로 출력될 수 있음을 보장합니다.",
      "show(30)에서 T가 정수로 정해집니다|Display 구현이 있는지 검사합니다|println!이 30을 표시합니다",
      "T=i32 추론 → Display 확인 → 30 출력",
      "지원하지 않는 타입을 제약 없이 출력할 수 있다고 생각함", "필요한 동작만 제네릭 타입에 요구함",
      {"c":"_Generic 또는 명시적 타입별 함수", "python":"덕 타이핑과 런타임 __str__", "rust":"T: Display trait bound"}),
    D(55, "module-test", "Python 모듈화와 assert", "python",
      'def total(values):\n    return sum(values)\nassert total([10, 20]) == 30\nprint("검증 완료")', "검증 완료", "assert", "print",
      "코드를 함수와 모듈로 나누더라도 예상 동작을 검사하는 자동 테스트가 있어야 안전하게 고칩니다.",
      "assert는 조건이 거짓일 때 예외를 내고, 조건이 참일 때는 다음 줄로 진행합니다.",
      "total에 두 값을 전달합니다|sum 결과 30을 기대값과 비교합니다|참이므로 검증 완료를 출력합니다",
      "[10,20] → total=30 → 조건 참 → 출력",
      "assert가 실패해도 다음 print가 실행된다고 생각함", "예상 결과를 작은 테스트로 고정",
      {"c":"테스트 main과 return 상태 검사", "python":"별도 test_*.py 또는 assert", "rust":"#[test]와 cargo test"}),
    D(56, "abstraction-review", "구조체·enum·테스트 회상", "rust",
      'struct Session { minutes: u32 }\nfn main() {\n    let s=Session{minutes:30};\n    assert_eq!(s.minutes,30);\n    println!("검증 완료");\n}', "검증 완료", "assert_eq!", "println!",
      "데이터 모델과 테스트를 함께 점검해 세 언어에서 같은 상태를 만들었는지 검증합니다.",
      "Session의 minutes는 u32이고 assert_eq!가 실제 값 30과 기대 30을 비교합니다.",
      "Session을 초기화합니다|필드 값과 기대값이 같아 단언이 통과합니다|검증 완료를 출력합니다",
      "s.minutes=30 → 기대값=30 → 통과",
      "검사하지 않은 예시 출력만 보고 구현이 맞다고 결론 냄", "구조화된 데이터에 회귀 테스트 추가",
      {"c":"struct와 assert.h", "python":"dataclass와 assert", "rust":"struct와 assert_eq!"}),
    D(58, "undo-stack", "실행 취소에 스택 적용", "python",
      'history = []\nhistory.append("입력")\nhistory.append("삭제")\nprint(history.pop())', "삭제", "pop()", "pop(0)",
      "가장 최근 작업부터 되돌리는 실행 취소는 스택의 후입선출 순서와 같습니다.",
      "append는 위에 쌓고 인자 없는 pop은 맨 위의 최신 작업을 제거해 돌려줍니다.",
      "입력을 저장합니다|그 위에 삭제를 쌓습니다|pop이 삭제를 반환하고 입력은 남습니다",
      "[] → [입력] → [입력,삭제] → 삭제 pop",
      "pop(0)으로 가장 오래된 작업을 먼저 제거함", "최근 작업부터 되돌림",
      {"c":"배열 끝 top과 용량 검사", "python":"list.append/pop()", "rust":"Vec::push/pop은 Option 반환"}),
    D(59, "queue", "큐와 선입선출", "python",
      'from collections import deque\nwaiting = deque(["A", "B"])\nwaiting.append("C")\nprint(waiting.popleft())', "A", "popleft()", "pop()",
      "먼저 접수한 요청을 먼저 처리해야 공정한 대기열이 됩니다.",
      "큐는 뒤에 넣고 앞에서 꺼냅니다. deque의 popleft는 오래된 항목을 O(1)에 꺼냅니다.",
      "A,B가 기다립니다|C가 뒤에 합류합니다|앞에 있는 A를 제거해 출력합니다",
      "[A,B] → [A,B,C] → A 처리",
      "pop()으로 마지막 접수 C를 먼저 처리함", "먼저 도착한 요청부터 처리",
      {"c":"원형 배열 head/tail 관리", "python":"collections.deque popleft", "rust":"VecDeque::pop_front"}),
    D(60, "circular-queue", "원형 큐의 머리·꼬리", "c",
      '#include <stdio.h>\nint main(void) {\n    int buffer[3] = {10,20,30};\n    int head = 2;\n    printf("%d\\n", buffer[(head + 1) % 3]);\n    return 0;\n}', "10", "(head + 1) % 3", "head + 1",
      "고정 배열을 대기열로 재사용하려면 끝에서 다시 처음으로 돌아가는 인덱스가 필요합니다.",
      "인덱스는 용량으로 나눈 나머지로 순환합니다. head=2의 다음 위치는 (2+1)%3=0입니다.",
      "head는 마지막 인덱스 2입니다|3%3으로 위치 0을 얻습니다|buffer[0]=10을 출력합니다",
      "head=2 → 다음 인덱스=0 → 값 10",
      "나머지 연산을 빼먹어 배열 경계를 넘음", "인덱스를 용량 안에서 순환시킴",
      {"c":"(index+1)%capacity와 full/empty 구별", "python":"deque가 내부 순환을 관리", "rust":"VecDeque가 head/tail 관리"}),
    D(61, "linked-list", "단일 연결 리스트의 다음 노드", "c",
      '#include <stdio.h>\ntypedef struct Node { int value; struct Node *next; } Node;\nint main(void) {\n    Node last={20,NULL}; Node first={10,&last};\n    printf("%d\\n", first.next->value);\n    return 0;\n}', "20", "first.next->value", "first.value",
      "노드가 다음 노드의 주소를 보유하면 메모리에서 연속되지 않아도 순서를 만들 수 있습니다.",
      "first.next는 last의 주소이고 ->는 포인터를 통해 last.value를 읽습니다.",
      "last는 값 20과 NULL을 가집니다|first의 next를 &last로 초기화합니다|다음 노드의 20을 출력합니다",
      "first(10) → next=&last → last(20) → 출력",
      "NULL인 next를 검사하지 않고 역참조함", "주소 링크를 따라 다음 노드 방문",
      {"c":"Node *next와 NULL 경계 검사", "python":"객체의 next 속성으로 참조 연결", "rust":"Option<Box<Node>>로 단일 소유 연결"}),
    D(62, "doubly-linked", "양방향 연결과 불변식", "python",
      'nodes = {"A": {"next": "B", "prev": None}, "B": {"next": None, "prev": "A"}}\nprint(nodes[nodes["B"]["prev"]]["next"])', "B", '["prev"]', '["next"]',
      "이전과 다음 방향 모두 이동하려면 두 링크를 같은 관계로 갱신해야 합니다.",
      "B.prev=A라면 A.next=B여야 합니다. 두 방향이 서로를 가리키는 것이 불변식입니다.",
      "B의 prev를 읽으면 A입니다|A의 next를 읽으면 B입니다|왕복 관계가 맞는지 출력합니다",
      "B.prev=A → A.next=B → 일치",
      "삽입·삭제 때 next만 바꾸고 prev를 갱신하지 않음", "앞뒤 링크 일치 유지",
      {"c":"Node *prev,*next를 함께 수정", "python":"참조 속성 양쪽 갱신", "rust":"소유권 때문에 인덱스 기반 Vec나 Rc<RefCell> 고려"}),
    D(63, "linear-review", "스택·큐·리스트 회상", "python",
      'from collections import deque\nq = deque([1, 2])\nq.append(3)\nprint(q.popleft(), q.pop())', "1 3", "popleft()", "pop()",
      "같은 자료를 어디서 넣고 빼느냐에 따라 FIFO와 LIFO가 달라지는지 확인합니다.",
      "앞에서 popleft 하면 가장 오래된 1, 뒤에서 pop 하면 가장 최근 3을 꺼냅니다.",
      "q=[1,2,3]입니다|앞의 1을 제거합니다|뒤의 3을 제거하고 둘을 출력합니다",
      "[1,2,3] → 앞 1 → 뒤 3",
      "큐 처리와 스택 처리를 같은 제거 연산으로 착각함", "자료구조의 제거 위치 구분",
      {"c":"head/tail 또는 top 인덱스 명시", "python":"popleft와 pop의 차이", "rust":"VecDeque::pop_front와 pop_back"}),
    D(64, "tree", "트리의 부모·자식 순회", "python",
      'tree = ("A", ("B", None, None), ("C", None, None))\ndef count(node):\n    return 0 if node is None else 1 + count(node[1]) + count(node[2])\nprint(count(tree))', "3", "node is None", "node == 0",
      "계층형 데이터는 부모가 자식을 가리키는 트리로 표현하고 재귀로 순회할 수 있습니다.",
      "빈 자식은 0개, 실제 노드는 자신 1개와 왼쪽·오른쪽 하위 트리 개수를 더합니다.",
      "A가 자신 1을 셉니다|B와 C가 각각 1을 셉니다|빈 자식들은 0이므로 합계 3입니다",
      "B=1 → C=1 → A=1+1+1=3",
      "빈 자식의 종료 조건을 빠뜨려 None을 인덱싱함", "하위 트리 결과를 합산",
      {"c":"Node* NULL 기저와 재귀", "python":"None 기저와 튜플 재귀", "rust":"Option<Box<Node>>와 match"}),
    D(65, "bst", "이진 탐색 트리의 비교 경로", "python",
      'tree = {8: (3, 10), 3: (None, None), 10: (None, None)}\nkey = 10\nnode = 8\nif key > node: node = tree[node][1]\nprint(node == key)', "True", "key > node", "key < node",
      "정렬 규칙이 있는 트리라면 한 번의 비교로 다음 탐색 방향을 정합니다.",
      "현재 노드보다 작은 키는 왼쪽, 큰 키는 오른쪽입니다. 중복 키 정책은 따로 정해야 합니다.",
      "루트 8과 목표 10을 비교합니다|10>8이라 오른쪽 자식 10으로 이동합니다|목표와 같아 True입니다",
      "root=8 → 오른쪽=10 → 발견",
      "정렬 불변식 없이 아무 트리에도 이분 탐색을 적용함", "키 비교로 가지 하나 선택",
      {"c":"struct Node*와 값 비교", "python":"노드 객체와 왼쪽/오른쪽 참조", "rust":"Option<Box<Node>>와 Ord"}),
    D(66, "heap", "힙과 우선순위 큐", "python",
      'import heapq\nwaiting = [30, 10, 20]\nheapq.heapify(waiting)\nprint(heapq.heappop(waiting))', "10", "heapify(waiting)", "waiting.sort()",
      "항상 가장 작은 작업을 먼저 처리해야 할 때 매번 전체를 정렬할 필요는 없습니다.",
      "최소 힙은 부모가 자식 이하라는 규칙을 유지하고 루트에서 최소값을 꺼냅니다.",
      "세 우선순위를 힙으로 재배열합니다|루트가 최소 10입니다|heappop이 10을 제거·반환합니다",
      "[30,10,20] → heapify 최소 루트 10 → pop 10",
      "힙 내부 배열 전체가 정렬돼 있다고 생각함", "최소 우선순위 추출",
      {"c":"배열 인덱스 2i+1,2i+2로 sift 구현", "python":"heapq의 최소 힙", "rust":"BinaryHeap은 기본 최대 힙, Reverse 사용"}),
    D(67, "hash-map", "해시 맵으로 횟수 세기", "python",
      'counts = {}\nfor topic in ["C", "Rust", "C"]:\n    counts[topic] = counts.get(topic, 0) + 1\nprint(counts["C"])', "2", "get(topic, 0)", "get(topic, 1)",
      "주제별 학습 횟수를 매번 처음부터 순회해 찾기보다 키로 집계할 수 있습니다.",
      "dict는 키를 해시해 값을 찾고, 첫 등장 때 기본값 0으로 시작해 1씩 증가시킵니다.",
      "처음 C는 0+1=1입니다|Rust도 1입니다|다시 C를 만나 1+1=2입니다",
      "C:0→1 → Rust:0→1 → C:1→2",
      "첫 등장 키의 기본값을 1로 주고 다시 1을 더함", "키별 빈도 누적",
      {"c":"해시 테이블 직접 구현 시 충돌 처리", "python":"dict.get 기본값 사용", "rust":"HashMap.entry(...).or_insert(0)"}),
    D(68, "graph", "그래프의 인접 목록", "python",
      'edges = {"A": ["B", "C"], "B": ["C"], "C": []}\nprint(edges["A"])', "['B', 'C']", '["A"]', '["C"]',
      "한 항목이 여러 항목과 연결될 때 트리의 단일 부모 규칙보다 일반적인 그래프가 필요합니다.",
      "인접 목록은 정점마다 바로 이어진 이웃의 목록을 저장합니다. 방향 그래프라면 A→B가 B→A를 뜻하지 않습니다.",
      "A의 이웃을 B,C로 등록합니다|B의 이웃은 C입니다|A 목록을 읽어 두 이웃을 출력합니다",
      "A→B,C → B→C → A 이웃 B,C",
      "방향 간선을 역방향에도 자동으로 있다고 간주함", "정점별 이웃 표현",
      {"c":"정점 인덱스와 동적 이웃 배열", "python":"dict[str,list[str]]", "rust":"HashMap<&str,Vec<&str>>"}),
    D(69, "bfs", "너비 우선 탐색과 방문 집합", "python",
      'from collections import deque\ngraph = {"A": ["B", "C"], "B": [], "C": []}\nq = deque(["A"]); seen = {"A"}\nwhile q:\n    node = q.popleft()\n    for next_node in graph[node]:\n        if next_node not in seen: seen.add(next_node); q.append(next_node)\nprint(sorted(seen))', "['A', 'B', 'C']", "q.popleft()", "q.pop()",
      "연결된 정점을 가까운 순서로 찾으려면 큐와 방문 집합을 함께 사용합니다.",
      "큐는 현재 거리의 정점을 먼저 처리하고 seen은 순환 간선에서 같은 정점을 다시 넣지 않게 합니다.",
      "A를 꺼냅니다|새 이웃 B,C를 방문 표시 후 큐에 넣습니다|둘을 처리하고 seen을 정렬해 출력합니다",
      "q=[A] → q=[B,C] → q=[] → seen={A,B,C}",
      "방문 표시를 늦춰 같은 노드가 큐에 여러 번 들어감", "가까운 정점부터 탐색",
      {"c":"배열 큐와 bool visited", "python":"deque와 set", "rust":"VecDeque와 HashSet"}),
    D(70, "structures-review", "자료구조 선택 회상", "python",
      'from collections import deque\nwork = deque(["first", "second"])\nprint(work.popleft())', "first", "popleft()", "pop()",
      "문제의 입력·제거 순서를 보고 스택·큐·트리·해시 중 무엇을 고를지 말로 정리합니다.",
      "접수 순서 보존이 불변식이라면 앞에서 꺼내는 큐가 맞습니다.",
      "first가 먼저 들어왔습니다|second가 뒤에 있습니다|popleft가 first를 처리합니다",
      "first 대기 → second 대기 → first 처리",
      "최근 항목 pop을 써서 접수 순서를 뒤집음", "처리 순서에 맞는 구조 선택",
      {"c":"원형 큐로 FIFO 구현", "python":"deque.popleft", "rust":"VecDeque::pop_front"}),
    D(71, "complexity", "시간 복잡도와 입력 크기", "python",
      'values = [2, 4, 6, 8]\nsteps = 0\nfor value in values:\n    steps += 1\nprint(steps)', "4", "steps += 1", "steps += 2",
      "입력 크기가 커질 때 작업 수가 어떻게 늘어나는지 봐야 자료구조와 알고리즘을 비교할 수 있습니다.",
      "원소 n개를 한 번씩 방문하면 작업 수가 n에 비례하므로 O(n)입니다. 실제 시간과 상수는 따로 측정합니다.",
      "배열 길이는 4입니다|각 원소를 방문할 때 steps를 1 올립니다|4번 방문 후 4를 출력합니다",
      "0 → 1 → 2 → 3 → 4",
      "O(n)을 실제 실행 시간이 정확히 n초라는 뜻으로 착각함", "입력 크기와 작업 수의 증가율 파악",
      {"c":"루프 반복 횟수 n을 세기", "python":"for 순회 횟수 n", "rust":"iterator가 n개 원소를 방문"}),
    D(72, "binary-search", "정렬 배열의 이진 탐색", "python",
      'values = [2, 4, 6, 8, 10]\ntarget = 8\nlo, hi = 0, len(values)\nwhile lo < hi:\n    mid = (lo + hi) // 2\n    if values[mid] < target: lo = mid + 1\n    else: hi = mid\nprint(lo)', "3", "lo = mid + 1", "lo = mid",
      "정렬된 데이터에서 중간 값을 비교하면 탐색 범위를 절반씩 줄일 수 있습니다.",
      "반열린 범위 [lo,hi)에서 target 이상이 처음 나타나는 위치를 유지합니다.",
      "중간 인덱스 2의 값 6이 작아 lo=3입니다|새 중간 4의 값 10은 크므로 hi=4입니다|인덱스 3의 8에서 수렴합니다",
      "[0,5) → [3,5) → [3,4) → 위치 3",
      "정렬되지 않은 배열에 이진 탐색을 적용함", "정렬된 범위를 반으로 축소",
      {"c":"size_t lo,hi와 overflow 없는 mid", "python":"lo/hi 반열린 구간", "rust":"slice.binary_search 또는 partition_point"}),
    D(73, "insertion-sort", "삽입 정렬의 정렬된 접두부", "python",
      'values = [3, 1, 2]\nfor i in range(1, len(values)):\n    key = values[i]; j = i - 1\n    while j >= 0 and values[j] > key:\n        values[j + 1] = values[j]; j -= 1\n    values[j + 1] = key\nprint(values)', "[1, 2, 3]", "values[j] > key", "values[j] < key",
      "작은 입력이나 거의 정렬된 입력은 정렬된 앞부분에 새 값을 끼워 넣는 방식이 직관적입니다.",
      "반복 시작 때 [0,i)는 정렬돼 있고 key보다 큰 값만 한 칸씩 오른쪽으로 밉니다.",
      "첫 key 1이 3 앞에 들어갑니다|다음 key 2가 1과 3 사이에 들어갑니다|전체가 [1,2,3]입니다",
      "[3,1,2] → [1,3,2] → [1,2,3]",
      "비교 방향을 반대로 써 내림차순으로 정렬함", "정렬된 접두부 불변식 유지",
      {"c":"배열 원소 이동과 인덱스 경계", "python":"제자리 리스트 원소 이동", "rust":"slice.sort는 표준 구현, 교육용 이동은 소유권 주의"}),
    D(74, "merge-sort", "병합 정렬의 분할·병합", "python",
      'def merge_sort(values):\n    if len(values) < 2: return values\n    mid = len(values) // 2\n    a, b = merge_sort(values[:mid]), merge_sort(values[mid:])\n    out = []; i = j = 0\n    while i < len(a) and j < len(b):\n        if a[i] <= b[j]: out.append(a[i]); i += 1\n        else: out.append(b[j]); j += 1\n    return out + a[i:] + b[j:]\nprint(merge_sort([4, 1, 3, 2]))', "[1, 2, 3, 4]", "a[i] <= b[j]", "a[i] >= b[j]",
      "큰 배열을 정렬하려면 반으로 나눈 뒤 이미 정렬된 두 부분을 합칠 수 있습니다.",
      "길이가 1 이하인 부분은 이미 정렬됐습니다. 나머지는 반으로 나눈 뒤 두 정렬된 부분의 앞 원소를 비교하며 병합합니다.",
      "길이 2 미만을 기저로 둡니다|[4,1]과 [3,2]를 각각 [1,4], [2,3]으로 정렬합니다|두 부분의 i,j 인덱스를 비교해 작은 값을 옮깁니다|남은 부분을 붙여 최종 결과를 만듭니다",
      "[4,1,3,2] → [1,4]+[2,3] → [1,2,3,4]",
      "부분 배열의 정렬이 끝나기 전에 병합하거나 남은 꼬리를 빠뜨림", "분할한 부분을 정렬해 병합",
      {"c":"보조 배열에 O(n) 병합", "python":"인덱스로 두 부분 병합, O(n log n)", "rust":"slice 분할 후 임시 Vec에 병합"}),
    D(75, "partition", "퀵 정렬의 분할 기준", "python",
      'def quick_sort(values):\n    if len(values) < 2: return values\n    pivot = values[0]\n    less = [v for v in values[1:] if v < pivot]\n    more = [v for v in values[1:] if v >= pivot]\n    return quick_sort(less) + [pivot] + quick_sort(more)\nprint(quick_sort([4, 1, 3, 2, 3]))', "[1, 2, 3, 3, 4]", "v >= pivot", "v > pivot",
      "퀵 정렬은 기준보다 작은 구역과 나머지를 나누는 분할 연산이 핵심입니다.",
      "첫 값을 피벗으로 뽑고 나머지를 작은 값과 이상인 값으로 나눕니다. 각 부분을 다시 정렬해 피벗 양쪽에 붙입니다.",
      "원소가 하나면 그대로 반환합니다|피벗 4 아래에 1,3,2,3이 모입니다|다음 피벗 1·3이 각각 부분을 나눕니다|재귀 결과를 합쳐 중복 3을 모두 유지합니다",
      "[4,1,3,2,3] → 피벗4 → 피벗3 → [1,2,3,3,4]",
      "피벗과 같은 값을 두 그룹 모두에서 제외해 중복 원소를 잃음", "피벗 기준 분할 후 재귀적으로 정렬",
      {"c":"인덱스 교환으로 제자리 분할", "python":"학습용 새 리스트 분할, 평균 O(n log n)·최악 O(n²)", "rust":"partition 또는 두 Vec로 분할"}),
    D(76, "divide-conquer", "분할 정복의 재귀 결합", "python",
      'def maximum(values):\n    if len(values) == 1: return values[0]\n    mid = len(values) // 2\n    return max(maximum(values[:mid]), maximum(values[mid:]))\nprint(maximum([3, 9, 2, 7]))', "9", "len(values) == 1", "len(values) == 0",
      "하나의 큰 문제를 두 하위 문제로 나누고 각각의 답을 결합하는 사고가 여러 알고리즘의 공통 뼈대입니다.",
      "원소 하나인 부분은 답이 바로 그 값이고 두 절반의 최대 중 큰 것이 전체 최대입니다.",
      "[3,9]의 최대는 9입니다|[2,7]의 최대는 7입니다|둘을 비교해 9를 반환합니다",
      "[3,9,2,7] → max(3,9)=9 + max(2,7)=7 → 9",
      "빈 입력 처리 정책 없이 길이 0의 배열도 호출함", "부분 답을 결합해 전체 답 생성",
      {"c":"시작·끝 인덱스를 재귀에 전달", "python":"슬라이스 복사는 추가 비용", "rust":"&slice[..mid]로 복사 없이 분할"}),
    D(77, "search-sort-review", "탐색·정렬 회상", "python",
      'values = sorted([8, 2, 6, 4])\nprint(values.index(6))', "2", "sorted(", "list(",
      "탐색 알고리즘의 전제인 정렬 상태와 정렬 결과를 직접 점검합니다.",
      "sorted는 새 정렬 리스트를 만들고 index는 그 리스트에서 목표의 위치를 찾습니다.",
      "입력 [8,2,6,4]가 정렬되어 [2,4,6,8]이 됩니다|6을 찾으면 인덱스 2입니다",
      "원본 → [2,4,6,8] → 6은 2번",
      "원본도 sorted 호출만으로 바뀐다고 생각함", "정렬 전후 탐색 위치 구분",
      {"c":"qsort 후 bsearch 또는 직접 순회", "python":"sorted가 새 리스트 생성", "rust":"sort는 슬라이스를 제자리 변경"}),
    D(78, "greedy", "그리디 선택과 반례", "python",
      'coins = [5, 1]\nremaining = 11\nused = []\nfor coin in coins:\n    while remaining >= coin: remaining -= coin; used.append(coin)\nprint(used)', "[5, 5, 1]", "remaining >= coin", "remaining > coin",
      "매 순간 가장 큰 선택을 하는 전략이 언제 맞는지 반례와 함께 판단해야 합니다.",
      "큰 동전을 먼저 고르는 규칙은 5·1 체계에서 11에 3개지만 임의 동전 체계에서 최적을 보장하지 않습니다.",
      "11에서 5를 두 번 빼 1이 남습니다|1을 한 번 뺍니다|세 동전 [5,5,1]을 출력합니다",
      "11 → 6 → 1 → 0",
      "모든 동전 체계에서 큰 동전부터 고르면 최적이라고 일반화함", "국소 선택의 최적성 조건 확인",
      {"c":"동전 배열을 큰 순서로 순회", "python":"while로 선택 반복", "rust":"조건 검사 후 남은 금액 갱신"}),
    D(79, "dynamic-programming", "DP로 중복 계산 줄이기", "python",
      'ways = [0] * 5\nways[0] = 1\nfor step in range(1, 5):\n    ways[step] = ways[step-1] + (ways[step-2] if step >= 2 else 0)\nprint(ways[4])', "5", "ways[step-1]", "ways[step-2]",
      "계단을 한 칸·두 칸 오르는 경우 수처럼 동일한 작은 문제를 여러 번 쓰면 결과를 저장해 재사용합니다.",
      "ways[n]은 n칸까지 오는 경우 수이며 마지막 이동은 n-1 또는 n-2에서 옵니다.",
      "ways[0]=1입니다|ways[1..4]가 1,2,3,5가 됩니다|4칸 경우 수 5를 출력합니다",
      "ways[0]=1 → 1 → 2 → 3 → 5",
      "기저 경우 수 0을 0으로 두어 모든 값이 0이 됨", "작은 문제의 답을 저장해 결합",
      {"c":"크기 n+1 배열과 경계 검사", "python":"리스트를 위에서 아래로 채움", "rust":"Vec<usize>와 인덱스 검사"}),
    D(80, "backtracking", "백트래킹과 되돌리기", "python",
      'results = []\ndef visit(path, remaining):\n    if not remaining:\n        results.append(tuple(path)); return\n    for x in remaining:\n        path.append(x)\n        visit(path, [v for v in remaining if v != x])\n        path.pop()\nvisit([], [1, 2])\nprint(results)', "[(1, 2), (2, 1)]", "path.pop()", "path.append(x)",
      "가능한 순열을 모두 찾으려면 선택하고 탐색한 뒤 이전 상태로 돌아와 다른 선택을 해야 합니다.",
      "path에 넣은 값을 재귀 호출 뒤 반드시 빼야 다음 가지가 같은 시작 상태에서 출발합니다.",
      "1을 먼저 넣어 (1,2)를 저장합니다|pop으로 비운 뒤 2를 선택합니다|(2,1)을 저장합니다",
      "[] → [1,2] 기록 → []로 복귀 → [2,1] 기록",
      "되돌리기 pop을 빼먹어 다른 가지의 경로가 섞임", "선택·탐색·취소의 대칭 유지",
      {"c":"배열 경로 길이를 감소시키며 복구", "python":"append/재귀/pop", "rust":"Vec::push/재귀/pop으로 상태 복구"}),
    D(81, "dfs", "깊이 우선 탐색과 순환", "python",
      'graph = {"A": ["B"], "B": ["C"], "C": ["A"]}\nseen = set()\ndef dfs(node):\n    if node in seen: return\n    seen.add(node)\n    for nxt in graph[node]: dfs(nxt)\ndfs("A")\nprint(len(seen))', "3", "seen.add(node)", "seen.remove(node)",
      "그래프에는 사이클이 있으므로 깊게 따라가더라도 방문 표시 없이는 끝나지 않을 수 있습니다.",
      "DFS는 이웃을 재귀적으로 끝까지 따라가고 이미 방문한 정점은 즉시 반환합니다.",
      "A를 표시하고 B로 갑니다|B를 표시하고 C로 갑니다|C의 다음 A는 이미 방문해 돌아옵니다",
      "A 방문 → B 방문 → C 방문 → A 재방문 차단",
      "방문 표시를 빼고 A→B→C→A 사이클에서 무한 재귀함", "사이클을 차단하며 깊이 탐색",
      {"c":"visited 배열과 재귀 또는 명시적 스택", "python":"seen 집합과 재귀", "rust":"HashSet과 &graph 빌림"}),
    D(82, "shortest-path", "최단 경로의 거리 갱신", "python",
      'import heapq\ngraph = {"A": [("B", 2), ("C", 5)], "B": [("C", 1)], "C": []}\ndist = {name: float("inf") for name in graph}; dist["A"] = 0\nheap = [(0, "A")]\nwhile heap:\n    cost, node = heapq.heappop(heap)\n    if cost != dist[node]: continue\n    for next_node, weight in graph[node]:\n        if cost + weight < dist[next_node]:\n            dist[next_node] = cost + weight\n            heapq.heappush(heap, (dist[next_node], next_node))\nprint(dist["C"])', "3", "cost + weight < dist[next_node]", "cost + weight > dist[next_node]",
      "더 짧은 경로를 발견하면 기존 거리보다 작은 값으로 갱신해야 합니다.",
      "음수가 없는 간선에서는 현재까지 가장 짧은 후보부터 꺼냅니다. 이웃 경로가 기존 거리보다 짧으면 거리와 우선순위 큐를 갱신합니다.",
      "모든 거리를 무한대로 시작하고 A만 0으로 둡니다|큐에서 A를 꺼내 B=2,C=5로 기록합니다|B에서 C의 새 후보 3을 발견해 갱신합니다|오래된 C=5 후보는 건너뛰고 3을 출력합니다",
      "A=0 → B=2,C=5 → B 경유 C=3 → C=3",
      "음수 간선에도 다익스트라의 확정 규칙을 그대로 적용함", "더 짧은 후보로 거리 완화",
      {"c":"거리 배열과 INF 처리", "python":"dict 거리와 min 갱신", "rust":"우선순위 큐에 Reverse 비용 사용"}),
    D(83, "capstone-contract", "프로젝트 계약: 공통 CSV 입력", "python",
      'header = "date,language,topic,minutes,result"\nfields = header.split(",")\nprint(len(fields), fields[3])', "5 minutes", "split(\",\")", "split(\";\")",
      "세 언어로 같은 프로그램을 만들려면 먼저 필드 순서와 출력 규약을 한 가지로 고정해야 합니다.",
      "CSV 한 행은 날짜·언어·주제·분·결과의 다섯 열이고 minutes는 네 번째 열입니다.",
      "헤더 문자열을 쉼표로 나눕니다|다섯 항목을 얻습니다|인덱스 3의 minutes를 출력합니다",
      "헤더 → 다섯 열 → 네 번째 minutes",
      "쉼표가 포함된 인용 필드를 단순 split으로 실제 CSV처럼 처리함", "공통 입력 스키마 정의",
      {"c":"CSV 파서에 열 개수·인용 규칙 전달", "python":"csv.DictReader가 표준 CSV 처리", "rust":"csv crate 또는 제약된 형식의 명시적 파서"}),
    D(84, "fixture-review", "공통 fixture와 오류 사례 설계", "python",
      'rows = [("C", 30), ("Rust", 20), ("C", 10)]\nprint(sum(minutes for language, minutes in rows if language == "C"))', "40", 'language == "C"', 'language != "C"',
      "세 구현이 같은 결과를 내는지 확인하려면 입력 fixture와 기대 출력을 먼저 고정합니다.",
      "C 행 두 개의 분을 더하면 40이고 Rust 행은 필터에서 제외됩니다.",
      "첫 C에서 30을 얻습니다|Rust는 건너뜁니다|두 번째 C의 10을 더해 40입니다",
      "C 30 → Rust 제외 → C 10 → 40",
      "필터를 적용한 결과와 전체 합계를 같은 값으로 비교함", "공통 fixture의 필터 기대값 계산",
      {"c":"같은 csv 파일로 C 결과 비교", "python":"필터와 sum 기대값 고정", "rust":"같은 fixture를 cargo test에서 읽기"}),
    D(85, "python-csv-parse", "Python CSV 파싱과 검증", "python",
      'import csv, io\nsource = io.StringIO("date,language,topic,minutes,result\\n2026-10-01,Python,변수,30,pass\\n")\nrow = next(csv.DictReader(source))\nminutes = int(row["minutes"])\nprint(minutes)', "30", 'int(row["minutes"])', 'row["minutes"]',
      "CSV의 모든 필드는 글자이므로 숫자·날짜·언어·결과를 명시적으로 검증해야 합니다.",
      "DictReader는 헤더 이름으로 필드를 읽고 int는 minutes를 정수로 변환하며 잘못된 값이면 실패합니다.",
      "헤더로 열 이름을 인식합니다|첫 데이터 행을 사전으로 읽습니다|minutes 문자열 30을 정수 30으로 바꿉니다",
      "CSV 문자열 → row['minutes']='30' → int=30",
      "검증 없이 음수·누락·알 수 없는 언어를 정상 행으로 취급함", "CSV 레코드 필드별 검증",
      {"c":"토큰화 후 strtol·날짜 범위 검사", "python":"csv.DictReader와 ValueError", "rust":"필드 분리 후 parse::<u32>()의 Result"}),
    D(86, "python-aggregate", "Python 집계·정렬·Top N", "python",
      'rows = [("C", 30), ("Python", 45), ("C", 15)]\ntotals = {}\nfor name, minutes in rows: totals[name] = totals.get(name, 0) + minutes\nprint(sorted(totals.items(), key=lambda row: (-row[1], row[0]))[0])', "('C', 45)", 'totals.get(name, 0)', 'totals.get(name, 1)',
      "필터 후 언어별 분을 합치고 동률일 때 정렬 기준까지 정해야 세 언어의 출력이 같습니다.",
      "사전은 언어별 누적값을 저장하고 정렬 키는 합계 내림차순, 언어 이름 오름차순입니다.",
      "C 30을 기록합니다|Python 45와 C의 추가 15로 둘 다 45입니다|동률에서 C가 앞서 첫 항목입니다",
      "C=30 → Python=45 → C=45 → 동률은 이름순 C",
      "동률 순서를 명시하지 않아 구현 언어마다 Top N이 달라짐", "그룹별 합계와 결정적 정렬",
      {"c":"집계 배열과 비교 함수에 tie-breaker", "python":"dict 집계 후 sorted 키", "rust":"BTreeMap 또는 정렬 Vec와 tie-breaker"}),
    D(87, "c-csv-parse", "C 입력 검증과 정수 변환", "c",
      '#include <stdio.h>\n#include <stdlib.h>\nint main(void) {\n    char *end = NULL;\n    long minutes = strtol("30", &end, 10);\n    if (!end || *end != \'\\0\' || minutes <= 0) return 1;\n    printf("%ld\\n", minutes);\n    return 0;\n}', "30", "*end != '\\0'", "*end == '\\0'",
      "C는 숫자 필드 끝에 글자가 남았는지 직접 확인해야 잘못된 CSV 값을 받아들이지 않습니다.",
      "strtol은 숫자를 읽은 마지막 위치를 end에 넣고 *end가 널일 때만 입력 전체가 숫자입니다.",
      "30을 10진수 30으로 바꿉니다|end는 문자열 끝을 가리킵니다|양수와 종료 문자를 확인해 출력합니다",
      "입력 30 → minutes=30 → end는 끝 → 성공",
      "atoi로 오류·남은 문자·범위를 구분하지 못함", "숫자 필드의 완전한 파싱 검사",
      {"c":"strtol + endptr + errno 경계 검사", "python":"int와 범위 검사", "rust":"parse::<u32>()와 Result"}),
    D(88, "c-aggregation", "C 레코드 집계와 경계 검사", "c",
      '#include <stdio.h>\nint main(void) {\n    int minutes[] = {30, 20, 10};\n    int total = 0;\n    for (int i = 0; i < 3; i++) total += minutes[i];\n    printf("%d\\n", total);\n    return 0;\n}', "60", "i < 3", "i <= 3",
      "C 구현에서도 공통 fixture의 전체 공부 시간과 필터별 시간을 정확히 맞춰야 합니다.",
      "현재 합계 total에 각 유효 인덱스의 값을 한 번씩 더합니다. 마지막 유효 인덱스는 2입니다.",
      "total=0입니다|30,20,10을 순서대로 누적합니다|합계 60을 출력합니다",
      "0 → 30 → 50 → 60",
      "배열 길이와 인덱스의 경계를 혼동해 원소를 하나 더 읽음", "레코드 시간 합계 누적",
      {"c":"정수 overflow 검사와 입력 배열 길이", "python":"sum(row.minutes for row in rows)", "rust":"checked_add로 합계 overflow 처리"}),
    D(89, "rust-record-parse", "Rust 타입으로 레코드 검증", "rust",
      'struct Session { minutes: u32 }\nfn main() {\n    let raw = "30";\n    let session = Session { minutes: raw.parse().expect("분 숫자 오류") };\n    println!("{}", session.minutes);\n}', "30", "raw.parse()", "raw.len()",
      "CSV 문자열을 타입이 있는 Session으로 만들 때 파싱 실패를 호출자에게 전달해야 합니다.",
      "minutes:u32를 기대하는 필드에서 parse가 숫자 변환을 하고 실패하면 Err가 됩니다.",
      "raw는 문자열 30입니다|parse로 u32 30을 얻습니다|Session의 필드로 저장해 출력합니다",
      "raw='30' → parse Ok(30) → Session.minutes=30",
      "실제 파일 파서에서 expect로 전체 프로그램을 종료하고 어느 행인지 숨김", "텍스트 행을 타입 있는 레코드로 변환",
      {"c":"struct Session과 검증 함수", "python":"dataclass Session과 int 변환", "rust":"struct Session과 Result 반환"}),
    D(90, "rust-aggregate", "Rust iterator 집계와 정렬", "rust",
      'fn main() {\n    let minutes = [30u32, 20, 10];\n    let total: u32 = minutes.iter().sum();\n    println!("{total}");\n}', "60", "iter().sum()", "iter().count()",
      "Rust에서도 동일한 fixture의 합계와 정렬 결과를 비교해 언어 간 기능 동등성을 지킵니다.",
      "iter는 값들을 차례로 빌려주고 sum은 누적합을 돌려줍니다. 큰 입력에선 overflow 정책도 따로 정합니다.",
      "30,20,10을 배열에 둡니다|iter가 세 값을 읽습니다|sum이 60을 계산합니다",
      "30 → 50 → 60",
      "배열 길이를 합계와 혼동하거나 release overflow 정책을 가정함", "iterator로 합계 계산",
      {"c":"for 합산과 정수 범위 검사", "python":"sum(minutes)", "rust":"iter().sum(), 필요 시 try_fold+checked_add"}),
    D(91, "cross-language-review", "세 구현의 결과 일치 검사", "python",
      'expected = {"total": 60, "count": 3}\nactual = {"count": 3, "total": 60}\nprint(actual == expected)', "True", "actual == expected", "actual is expected",
      "동일 입력에서 출력이 같아야 하므로 공백보다 먼저 구조화된 결과의 값과 정렬 규칙을 비교합니다.",
      "사전의 ==는 항목의 순서가 달라도 키와 값이 모두 같으면 참입니다.",
      "expected와 actual에 같은 두 키·값이 들어 있습니다|순서는 달라도 값 비교가 성공합니다|True를 출력합니다",
      "두 결과의 키·값 일치 → True",
      "객체 동일성 is로 독립된 결과의 값 일치를 검사함", "공통 fixture 기대값 비교",
      {"c":"출력 파싱 또는 기준 출력 파일 비교", "python":"dict 값 비교와 테스트", "rust":"PartialEq를 가진 struct 비교"}),
    D(92, "capstone-release", "완성 프로젝트 검증과 확장", "python",
      'sessions = [("C", 30), ("Python", 20), ("Rust", 10)]\ntotal = sum(minutes for _, minutes in sessions)\nassert total == 60\nprint("Study Log Analyzer 완료:", total)', "Study Log Analyzer 완료: 60", "assert total == 60", "assert total == 0",
      "마지막 날은 세 언어 구현의 입력 검증·집계·필터·정렬·오류 메시지를 같은 fixture로 검증합니다.",
      "공통 명세가 참인지 테스트로 고정한 후 선호 언어에서 ASCII 시각화 한 가지를 추가합니다.",
      "세 기록의 시간을 합해 60을 구합니다|assert로 공통 기대값을 확인합니다|완료 메시지를 출력합니다",
      "C30 + Python20 + Rust10 → 60 → 테스트 통과",
      "한 언어의 결과만 보고 나머지 구현도 같다고 가정함", "동일 입력·출력 명세와 테스트 완료",
      {"c":"독립 실행 파일의 기준 출력·오류 검증", "python":"pytest/unittest와 선택 확장", "rust":"cargo test와 동일 fixture 비교"}),
]}
